name: random_item
applicationId: "com.yf.randomitem"
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.1+7

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  file_picker: ^9.2.1
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
